services:
  gateway-server:
    container_name: gateway-server
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - GPR_USER
        - GPR_TOKEN
    ports:
      - "8090:8090"
    env_file:
      - .env.runtime
    networks:
      - pgsg-network

networks:
  pgsg-network:
    external: true

secrets:
  GPR_USER:
    environment: GPR_USER
  GPR_TOKEN:
    environment: GPR_TOKEN
