upstream gateway {
    least_conn;
    server 10.0.0.10:8090 max_fails=3 fail_timeout=10s;  # gateway-server-1
    server 10.0.0.20:8090 max_fails=3 fail_timeout=10s;  # gateway-server-2
    server 10.0.0.30:8090 max_fails=3 fail_timeout=10s;  # gateway-server-3
}

server {
    listen 80;

    # 게이트웨이 관련 리버스 프록시 설정 추가
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Connection "";
        proxy_pass http://gateway;
    }
}